spring.application.name=backend
server.port=9090
spring.datasource.url=jdbc:postgresql://ep-sparkling-meadow-aywf5l81-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.openai.api-key=${AI_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.embedding.model=openai/text-embedding-3-small
file.upload-dir=/uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.ai.openai.chat.model=deepseek/deepseek-v4-flash-0731
